In [5]:
#qn 1
import numpy as np
arr= np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [15]:
#qn 2

import numpy as np
l1=[]
l2=[]
i=0
j=0
while(i<5):
  n=int(input())
  l1.append(n)
  i=i+1
while(j<5):
  n=int(input())
  l2.append(n)
  j=j+1
a1=np.array(l1)
a2=np.array(l2)
a3=np.concatenate((a1,a2),axis=0)
print(a3)
a4=np.sort(a3)
print(a4)


2
4
6
8
10
1
3
5
7
9
[ 2  4  6  8 10  1  3  5  7  9]
[ 1  2  3  4  5  6  7  8  9 10]


In [17]:
#qn 3

import numpy as np
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5],[3,6,9]] )
print(arr.ndim)
print(arr.size)


2
9


In [22]:
#qn 4

#We can convert the dimension using reshape function

l1=[]
i=0
while(i<10):
  n=input()
  l1.append(n)
  i=i+1
arr = np.array(l1)
n=input()
arr_2d = np.reshape(arr, (2,5))
print(arr_2d)


1
2
3
4
5
6
7
8
9
0
2
[['1' '2' '3' '4' '5']
 ['6' '7' '8' '9' '0']]
